### ISSUE TITLE
not able to teleport after using hand-tracking-controls

### ISSUE THREAD

**Issue by addy1997** [gftruj/aframe-hand-tracking-controls-extras#3]
Hi @gftruj,

I am trying to teleport in my VR scene using the [blink-controls component](https://github.com/jure/aframe-blink-controls) (an alternative to the teleport controls component) along with the hand-tracking-controls component. 

I can't see the arc generating anywhere in the VR scene except the blue-colored ring that appears on the ground. I am not teleported anywhere.

I tried something like this, but it works partially (shown in the video below). The code snippet can be found below:

```
<a-entity id="leftHand" hand-tracking-controls="hand: left; modelColor: #ADD8E6; modelStyle: mesh" blink-controls="snapTurn:false; startEvents:pinchstarted; endEvents:pinchended; cameraRig: #camera-control; teleportOrigin: #camera-head; curveHitColor: #99ff99; curveMissColor: #ff0000; curveNumberPoints: 15; curveLineWidth: 0.05; curveShootingSpeed: 5; defaultPlaneSize: 100; landingMaxAngle: 45;"></a-entity>`
```
```
<a-entity id="rightHand" hand-tracking-controls="hand: right; modelColor: #ADD8E6; modelStyle: mesh" blink-controls="snapTurn:false; startEvents:pinchstarted; endEvents:pinchended; cameraRig: #camera-control; teleportOrigin: #camera-head; curveHitColor: #99ff99; curveMissColor: #ff0000; curveNumberPoints: 15; curveLineWidth: 0.05; curveShootingSpeed: 5; defaultPlaneSize: 100; landingMaxAngle: 45;"></a-entity>
```

https://github.com/jure/aframe-blink-controls/assets/29406906/3dba55a8-4787-4757-95ee-a05b41b25f57

Please could you help?

Thanks

**Comment by gftruj** [comment]
Hi, I'm currently AFK, I'll look into it (and the PR) next week :)

**Comment by addy1997** [comment]
Hey @gftruj,

Have you had a chance to take a look at this issue?

**Comment by addy1997** [comment]
Hi @gftruj,

can you please have a look at this issue?

**Comment by gftruj** [comment]
Two things got deprecated, the navigation example should be working now:

https://github.com/gftruj/aframe-hand-tracking-controls-extras/assets/17348360/8e97a1ae-c470-430c-aa15-d8eb426483ba

changed the filename to `aframe-hand-tracking-controls-extras-full.js`, need to revamp the whole thing a bit 😅

**Comment by addy1997** [comment]
Hi @gftruj,

Thanks for your reply. How can I use this component to pick up the objects in the scene?

**Comment by addy1997** [comment]
Hi @gftruj,

How to use this component to grab the objects in the scene? btw, the index.html file (in examples/forcegraph/index.html) is missing the a-scene tag
